package zw.co.hcpwebcommons.domain.enums;

public enum ExceptionCode {
    INVALID_EMAIL(1),
    INVALID_PHONE_NUMBER (2),
    EMAIL_NOT_FOUND(3),
    MOBILE_NUMBER_NOT_FOUND(4),
    USER_NOT_FOUND(5),
    USER_ALREADY_EXISTS(6),
    USERS_UNAVAILABLE(7),
    INVALID_USERNAME(8),
    INVALID_ID_NUMBER(9),
    INVALID_USER_PIN(10),
    ACTIVITY_NOT_FOUND(11),
    AUDIT_TRAIL_NOT_FOUND(12),
    ROLE_NOT_FOUND(13),
    LOGIN_ENTRY_UNAVAILABLE(14),
    USER_LOGIN_ENTRY_UNAVAILABLE(15),
    LOGIN_ENTRIES_UNVAILABLE(16),
    UNABLE_TO_PUSH_MEMBER(17),
    UNEXPECTED_ERROR(18),
    COVER_CONFLICT(19),
    INVALID_INPUT(20),
    USER_DEVICE_DETAILS_NOT_FOUND(21),
    USER_NOT_OTP_ENABLED(22),
    USER_ID_NOT_FOUND(23),
    USER_AUTHENTICATION_ERROR(24),
    MEMBER_NOT_FOUND(25),
    MEMBERS_UNAVAILABLE(26),
    BENEFICIARIES_UNAVAILABLE(27),
    BENEFICIARY_NOT_FOUND(28),
    PAYMENT_NOT_FOUND(29),
    PAYMENTS_UNAVAILABLE(30),
    POLICY_NUMBER_EXISTS(31),
    POLICIES_UNAVAILABLE(32),
    POLICY_NOT_FOUND(33);

    ExceptionCode(int i) {
    }
}