#live mobile app
server.port=6110

live dashboard
#server.port=6110

#test mobile app
#server.port=6111

#test dashboard
#server.port=6112

#spring.ai.ollama.base-url= http://localhost:11434
#spring.ai.ollama.chat.options.model= deepseek-r1:1.5b

#spring.datasource.url=jdbc:mysql://cashcollectionactual.cr20sycespww.eu-north-1.rds.amazonaws.com:3306/cash_collection?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare&allowPublicKeyRetrieval=true&useUnicode=true&character_set_server=utf8mb4

spring.datasource.url=jdbc:mysql://10.1.4.4:3306/cash_collection_live?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare&allowPublicKeyRetrieval=true&useUnicode=true&character_set_server=utf8mb4
spring.datasource.username=code
spring.datasource.password=foxcode*7Live.


#spring.datasource.url= jdbc:mysql://localhost:3306/cash-collection?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=


#
#spring.datasource.url=jdbc:mysql://google/cash_collection?cloudSqlInstance=cash-collection-424018:us-central1:cash-collection&socketFactory=com.google.cloud.sql.mysql.SocketFactory
#spring.jpa.properties.hibernate.default_schema = public
#spring.datasource.username=root
#spring.datasource.password=foxcode*7Live.
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#spring.datasource.url=jdbc:h2:mem:cash_collection
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create


jwt.aunthentication
jwt.secret=javainuse
jwt.http.request.header=Authorization

#server.ssl.enabled=true
#server.ssl.keyStoreType=JKS
#server.ssl.key-store=classpath:cashcollection.jks
#server.ssl.key-store-password=Foxcode@7

#workin blow
#server.ssl.enabled=true
#server.ssl.key-store=classpath:cert.pfx
#server.ssl.key-store-password=Parisc@7700
#server.ssl.key-store-type=PKCS12





fmllife.paynow.integration.id=16814
fmllife.paynow.integration.key=991aaa4d-49ee-4a6e-af34-96a33250e727

fmlhealth.paynow.integration.id=16814
fmlhealth.paynow.integration.key=991aaa4d-49ee-4a6e-af34-96a33250e727